version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'beta'
      MYSQL_USER: 'fassetbot'
      MYSQL_PASSWORD: 'my1beta2password3'
    volumes:
      - ./data:/var/lib/mysql
      - ./init.mysql.sql:/docker-entrypoint-initdb.d/init.mysql.sql # Initialization SQL file
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10